web:
  build: ./web/
  environment:
    APP_ENV: development
  ports:
   - "3069:3069"
  volumes:
   - ./web:/spredshot
  external_links:
   - "spredshot_elastic_1:elastic"
   - "spredshot_rabbit_1:rabbit"
   - "spredshot_mongo_1:mongo"
# scraper:
#   build: ./scraper/
#   environment:
#     APP_ENV: development
#   external_links:
#    - "spredshot_rabbit_1:rabbit"
listingposter:
  build: ./listing-poster/
  external_links:
   - "spredshot_rabbit_1:rabbit"
   - "spredshot_elastic_1:elastic"
listingpercolator:
  build: ./listing-percolator/
  external_links:
   - "spredshot_rabbit_1:rabbit"
   - "spredshot_elastic_1:elastic"
