web:
  build: ./web/
  environment:
    APP_ENV: development
  ports:
   - "3069:3069"
  links:
   - "elastic"
scraper:
  build: ./scraper/
  environment:
    APP_ENV: development
  links:
   - "rabbit"
listingposter:
  build: ./listing-poster/
  environment:
    RABBIT_EXCHANGE: app.listing.create
    ES_INDEX: equipment
    ES_TYPE: listings
  links:
   - "rabbit"
   - "elastic"

consul:
  image: progrium/consul
  ports:
   - "8400:8400"
   - "8500:8500"
   - "8600:53/udp"
  command: -server -bootstrap -ui-dir /ui
  hostname: node1
elastic:
  image: myelastic
  ports:
   - "9200:9200"
   - "9300:9300"
rabbit:
  image: rabbitmq:3.5.0-management
  ports:
   - "8080:15672"
   - "5672:5672"
