web:
  build: ./web/
  environment:
    APP_ENV: development
  ports:
   - "3069:3069"
  links:
   - "elastic"
scraperqueue:
  build: ./scraper-queue/
  ports:
   - "80:80"
  links:
   - "rabbit"
scraper:
  build: ./scraper/
  environment:
    APP_ENV: development
  links:
   - "elastic"
   - "web"


consul:
  image: progrium/consul
  ports:
   - "8400:8400"
   - "8500:8500"
   - "8600:53/udp"
  command: -server -bootstrap -ui-dir /ui
  hostname: node1
elastic:
  image: myelastic
  ports:
   - "9200:9200"
  links:
   - "consul"
rabbit:
  image: rabbitmq:3.5.0-management
  ports:
   - "8080:15672"
   - "5672:5672"
# postgres:
#   image: postgres:9.4
# redis:
#   image: redis:3.0
