rabbit:
  image: rabbitmq:3.5.0-management
  ports:
   - "8080:15672"
   - "5672:5672"
mongo:
  image: mongo:3.0
  ports:
   - "27017:27017"
elastic:
  build: ./elastic/
  ports:
   - "9200:9200"
   - "9300:9300"