rabbit:
  image: rabbitmq:3.5.6-management
  ports:
   - "8080:15672"
   - "5672:5672"
mongo:
  image: mongo:3.0.7
  ports:
   - "27017:27017"
elastic:
  build: ./elastic/
  ports:
   - "9200:9200"
   - "9300:9300"
logsene:
  image: sematext/sematext-agent-docker
  restart: always
  volumes:
   - /var/run/docker.sock:/var/run/docker.sock
  environment:
    HOSTNAME: "${HOSTNAME}"
    LOGSENE_TOKEN: 461ec6fd-2cb7-4475-93d7-3edbd51796e0
    SPM_TOKEN: 649bce6f-2c64-4cd6-a7e8-a7ec4a25ca20