jenkins:
  image: jenkins:latest
  ports:
   - "8080:8080"
   - "50000:50000"
  restart: always
  cpu_shares: 256
  container_name: spredshot_jenkins
  volumes:
   - /data/spredshot/jenkins:/var/jenkins_home
