curl -XPOST 'http://elastic:9200/equipment/listing/' -d @sample.json
curl -XPOST 'http://elastic:9200/equipment/listing/' -d @sample.json
curl -XPOST 'http://elastic:9200/equipment/listing/' -d @sample.json
curl -XPOST 'http://elastic:9200/equipment/listing/' -d @sample.json
curl -XPOST 'http://elastic:9200/equipment/listing/' -d @sample.json
curl -XPOST 'http://elastic:9200/equipment/listing/' -d @sample.json
curl -XPOST 'http://elastic:9200/equipment/listing/' -d @sample.json
curl -XPOST 'http://elastic:9200/equipment/listing/' -d @sample.json
curl -XPOST 'http://elastic:9200/equipment/listing/' -d @sample.json
curl -XPOST 'http://elastic:9200/equipment/listing/' -d @sample.json
